### ISSUE TITLE
How to make new effects

### ISSUE THREAD

**Issue by ghost** [Slikey/EffectLib#18]
I tried creating a new effect for my plugin... I copied the animatedabll effect  and everything works but there is an error here  display(particle, location.add(vector)); its wanting me to create a new method. I did that and put the particle in there and it didnt work. please help :) btw love the lib

**Comment by LCastr0** [comment]
Can you send the whole class code that you used to make your effect please? :)

**Comment by toxicmages** [comment]
package me.Ospery.Particles;

import java.awt.Color;

import org.bukkit.Location;
import org.bukkit.util.Vector;

import de.slikey.effectlib.Effect;
import de.slikey.effectlib.EffectManager;
import de.slikey.effectlib.EffectType;
import de.slikey.effectlib.util.MathUtils;
import de.slikey.effectlib.util.ParticleEffect;
import de.slikey.effectlib.util.VectorUtils;

public abstract class EpicCrate extends Effect implements Runnable{

	public ParticleEffect particle = ParticleEffect.RED_DUST;
	public int particles = 150;
	public int particlesPerIteration = 10;
	public float size = 1F;
	public float xFactor = 1F, yFactor = 2F, zFactor = 1F;
	public float xOffset, yOffset = 0.8F, zOffset;
	public double xRotation, yRotation, zRotation = 0;
	protected int step;
	 public Color color = null;
	
    public EpicCrate(EffectManager effectManager) {
        super(effectManager);
        this.type = EffectType.REPEATING;
        this.iterations = 500;
        this.period = 1;
    }
	@Override
	public void onRun(){
		Vector vector = new Vector();
		Location location = getLocation();
		 for (int i = 0; i < particlesPerIteration; i++) {
			 step++;
			 
			  float t = (MathUtils.PI / particles) * step;
	            float r = MathUtils.sin(t) * size;
	            float s = 2 * MathUtils.PI * t;

	            vector.setX(xFactor * r * MathUtils.cos(s) + xOffset);
	            vector.setZ(zFactor * r * MathUtils.sin(s) + zOffset);
	            vector.setY(yFactor * size * MathUtils.cos(t) + yOffset);

	            VectorUtils.rotateVector(vector, xRotation, yRotation, zRotation);

	            particle.display(location.add(vector), visibleRange, 0, 0, 0, 0, 0);
	            location.subtract(vector);
			 
		 }
	}

}

**Comment by LCastr0** [comment]
First thing: You don't need to implement Runnable. Extending effect will already do something like that.
And second, I see why your display thing doesn't work. Instead of
particle.display(location.add(vector), visibleRange, 0, 0, 0, 0, 0);
You should use
display(particle, location.add(vector));

:)
If you still need help, just reply to this issue and i'll check. Tell me if this works so I can close the issue :)
