### ISSUE TITLE
BigBang effect doesn't run

### ISSUE THREAD

**Issue by idkw** [Slikey/EffectLib#19]
Hello
I'm integrating your library in one my plugins, it's really great. COngratulations on that.
I have just a little trouble playing the BigBang effect.

Here is a code sample, it's doesn't show anything and there is no error in the console :

    EffectLib lib = EffectLib.instance();
    EffectManager em = new EffectManager(lib);
    BigBangEffect effect = new BigBangEffect(em);
    effect.setEntity(player); 
    effect.setLocation(player.getLocation());
    effect.setTarget(player.getLocation());
    effect.setTargetEntity(player);
    effect.start();
    em.disposeOnTermination();

**Comment by Darkfield** [comment]
Same for me, will author respond?

**Comment by NathanWolf** [comment]
Hey, sorry for not responding!

Offhand it looks like that "Usage" code is a little out of date, but .. ought to work still.

I updated the "Demo" code a while back, I think I missed this extra Usage example.

http://dev.bukkit.org/paste/12501/

Looking at it, though, the only difference seems to be passing in your Plugin instance to EffectManager, versus the EffectLib plugin instance. That is important, though, if you've building this into your plugin as a lib (like with Maven).

Could you both let me know if you're trying to integrate with EffectLib as a stand-alone plugin, or if you're trying to include it in your own plugin?

I'm going to update that Usage example now to be clearer, it's worth trying that. If it's still not working, I'd happy to try to build and run your code myself to see what's up.

**Comment by idkw** [comment]
I don't know. Its old now. I'm not using it anymore.

**Comment by NathanWolf** [comment]
Ok then - sorry for the late response. I think I'm the only one watching this repo at this point.

I'm going to close this issue- @Darkfield , if you'd like please open a new issue with details and I'll try and help yo out!
