### ISSUE TITLE
Release on SpigotMC

### ISSUE THREAD

**Issue by NathanWolf** [Slikey/EffectLib#24]
I'm hoping @Slikey sees this, I'm honestly not sure the best way to get in touch at this point :)

I'm wondering if it'd be ok to put up an EffectLib page on Spigotmc.com?

I'd also like to move the docs from dev.bukkit.org to the wiki, and maybe add an example plugin.

**Comment by Slikey** [comment]
Yes, of course. If you give me the link to the wiki I can update the thread and dev site.
Am 13.04.2016 01:28 schrieb Nathan Wolf <notifications@github.com>:I'm hoping @Slikey sees this, I'm honestly not sure the best way to get in touch at this point :)

I'm wondering if it'd be ok to put up an EffectLib page on Spigotmc.com?

I'd also like to move the docs from dev.bukkit.org to the wiki, and maybe add an example plugin.

**Comment by NathanWolf** [comment]
I don't think I actually need you to do anything since I've got access to the dev site, I just wanted to make sure you were ok with it, since I'd have to release it on spigotmc under my account.

The wiki will be right here, just the Wiki tab at the top :)

Thanks!
