### ISSUE TITLE
Where is LocationEffect? (is repo out of date?)

### ISSUE THREAD

**Issue by edasaki** [Slikey/EffectLib#25]
Is this repo out of date? I noticed that LocationEffect source isn't here, although it exists in version 4.2 of EffectLib. Looking through the source of the .jar compiled through Maven it appears that there are many effects that exist that aren't in this repository.

**Comment by NathanWolf** [comment]
This repo is not out of date, it's still the official EffectLib repo.

I think LocationEffect/EntityEffect have been gone for a long while. Those were not effects but base classes for effects, and they aren't segregated like that anymore.

It looks like my CI server wasn't doing a "mvn clean" is the problem... so all of those old unused classes were still getting packaged in the jar. I fixed that just now- thanks for pointing this out, I never would have noticed. I'm not in the habit of opening jars to look at classes (why are you doing that, btw?)

**Comment by edasaki** [comment]
I was working on my own effects and thought I might need LocationEffect for something and was like "ok let's see if it fits" and realized it wasn't on the repo :P Although I didn't end up needing it lol
