### ISSUE TITLE
Is there a better place we could chat?

### ISSUE THREAD

**Issue by Sashie** [Slikey/EffectLib#26]
I appoligise in advance for posting this here!! I wanted to ask you a few things relating to coding using the particle library you are using, I wanted to ask you because you have been working on effectlib for a quite a while and might know a thing or two about what i might be talking about xD.

Lets assuming i already have certain particle effects working and that some may or may not be copies of your effects xD, have you ever noticed any 'ghost particles' ?? what i mean by this is, say we are playing a long distance effect to a player of 32 distance(not that far) . in the map at location 0,0,0 out to where the particle is played there is a noticeable set of particles that sort of,, 'jump around' between 0,0,0 and that location. Ive searched the googles for similarities to this but to no avail.

Feel free to delete this post if you feel its inappropriate of me to ask you this,,, here of all places. :3
-Sashie

**Comment by NathanWolf** [comment]
I haven't seen that, no.. sounds like maybe the particle speed and/or offsets are set very high, maybe?

This is a fine place for now, spigot forums may be better though. :)

**Comment by NathanWolf** [comment]
... though clearly I'm not very quick to respond here, sorry! :(

**Comment by Sashie** [comment]
xD I just logged into my email for the first time in forever and saw that you had replies, thinking that i was going to be like a week late now i rushed over to reply!

 I was also thinking maybe its an odd client glitch, using a few different particle plugins i was getting the same odd behavior.
