### ISSUE TITLE
EXPLODE sound

### ISSUE THREAD

**Issue by BlackBeltPanda** [Slikey/EffectLib#28]
The "EXPLODE" sounds in the BigBangEffect and ExplodeEffect don't work in 1.9.

**Comment by NathanWolf** [comment]
There's not going to be a way to fix that while maintaining backwards compatibility.

If you are using config-based effects, just change it yourself in configs, else change it programmatically.

I may branch effectlib into 1.8/1.9 versions eventually but if like to avoid it for now.

**Comment by BlackBeltPanda** [comment]
Setting the sound to "ENTITY_GENERIC_EXPLODE" with BigBangEffect.sound still throws "java.lang.NoSuchFieldError: EXPLODE" and the effect doesn't seem to run.

**Comment by NathanWolf** [comment]
Ah, true enough. I have null'd it out for the latest dev build, will be released as 4.3 but is available here now:

http://jenkins.elmakers.com/job/EffectLib/86/
