### ISSUE TITLE
Explode effect is using 1.8 sound name and causes bugs due to lack of noise.

### ISSUE THREAD

**Issue by iarepandemonium** [Slikey/EffectLib#29]
Can't use explode effect because of this.

**Comment by NathanWolf** [comment]
Doh!

Ok well.. I just bumped EffectLib to 5.0 and it will now only be fully compatible with 1.9. You can get a build from my dev server here:

http://jenkins.elmakers.com/job/EffectLib/87/de.slikey$EffectLib/
