### ISSUE TITLE
Issue!

### ISSUE THREAD

**Issue by Miljonair12** [Slikey/EffectLib#32]
I got a Issue and i don't know the problem I have all the required plugins in my server but is still don't work properly! 

Config:
15.07 20:19:04 [Multicraft] Loading server properties
15.07 20:19:04 [Multicraft] Starting server!
15.07 20:19:04 [Multicraft] Loaded config for "Spigot 1.9.4"
15.07 20:19:05 [Multicraft] Updating eula.txt file
15.07 20:19:05 [Server] INFO Loading libraries, please wait...
15.07 20:19:08 [Server] INFO Starting minecraft server version 1.9.4
15.07 20:19:08 [Server] INFO Loading properties
15.07 20:19:08 [Server] INFO Default game type: SURVIVAL
15.07 20:19:09 [Server] INFO This server is running CraftBukkit version git-Spigot-4af49dc-4e19de1 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
15.07 20:19:09 [Server] INFO Server Ping Player Sample Count: 12
15.07 20:19:09 [Server] INFO Using 4 threads for Netty based IO
15.07 20:19:09 [Server] INFO Debug logging is disabled
15.07 20:19:09 [Server] INFO Generating keypair
15.07 20:19:09 [Server] INFO Starting Minecraft server on 178.20.170.103:25612
15.07 20:19:09 [Server] INFO Using epoll channel type
15.07 20:19:09 [Server] INFO Set PluginClassLoader as parallel capable
15.07 20:19:09 [Server] INFO Loading EffectLib v5.1-SNAPSHOT
15.07 20:19:09 [Server] INFO Loading WorldEdit v6.1.3;7a097ca
15.07 20:19:09 [Server] INFO Loading ViaVersion v0.9.2
15.07 20:19:09 [Server] INFO ViaVersion 0.9.2 is now loaded, injecting!
15.07 20:19:09 [Server] INFO Loading ProtocolLib v4.0.2
15.07 20:19:09 [Server] INFO Loading MineFortress v1.3.0
15.07 20:19:09 [Server] INFO Loading LibsDisguises v9.0.9
15.07 20:19:09 [Server] INFO Loading HolographicDisplays v2.2
15.07 20:19:09 [Server] INFO Enabling ProtocolLib v4.0.2
15.07 20:19:09 [Server] INFO Started structure compiler thread.
15.07 20:19:09 [Server] WARN **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
15.07 20:19:09 [Server] WARN The server will make no attempt to authenticate usernames. Beware.
15.07 20:19:09 [Server] WARN Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
15.07 20:19:09 [Server] WARN Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
15.07 20:19:09 [Server] WARN To change this, set "online-mode" to "true" in the server.properties file.
15.07 20:19:09 [Server] INFO **** Beginning UUID conversion, this may take A LONG time ****
15.07 20:19:09 [Server] INFO Preparing level "world"
15.07 20:19:09 [Server] INFO -------- World Settings For [world] --------
15.07 20:19:09 [Server] INFO Mob Spawn Range: 4
15.07 20:19:09 [Server] INFO Cactus Growth Modifier: 100%
15.07 20:19:09 [Server] INFO Cane Growth Modifier: 100%
15.07 20:19:09 [Server] INFO Melon Growth Modifier: 100%
15.07 20:19:09 [Server] INFO Mushroom Growth Modifier: 100%
15.07 20:19:09 [Server] INFO Pumpkin Growth Modifier: 100%
15.07 20:19:09 [Server] INFO Sapling Growth Modifier: 100%
15.07 20:19:09 [Server] INFO Wheat Growth Modifier: 100%
15.07 20:19:09 [Server] INFO NetherWart Growth Modifier: 100%
15.07 20:19:09 [Server] INFO Nerfing mobs spawned from spawners: false
15.07 20:19:09 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
15.07 20:19:09 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
15.07 20:19:09 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
15.07 20:19:09 [Server] INFO Random Lighting Updates: false
15.07 20:19:09 [Server] INFO Structure Info Saving: true
15.07 20:19:09 [Server] INFO Max Entity Collisions: 8
15.07 20:19:09 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
15.07 20:19:09 [Server] INFO Max TNT Explosions: 100
15.07 20:19:09 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
15.07 20:19:09 [Server] INFO Item Despawn Rate: 6000
15.07 20:19:09 [Server] INFO Item Merge Radius: 2.5
15.07 20:19:09 [Server] INFO Arrow Despawn Rate: 1200
15.07 20:19:09 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
15.07 20:19:09 [Server] INFO View Distance: 10
15.07 20:19:09 [Server] INFO Zombie Aggressive Towards Villager: true
15.07 20:19:09 [Server] INFO Experience Merge Radius: 3.0
15.07 20:19:10 [Server] INFO -------- World Settings For [world_nether] --------
15.07 20:19:10 [Server] INFO Mob Spawn Range: 4
15.07 20:19:10 [Server] INFO Cactus Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Cane Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Melon Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Mushroom Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Pumpkin Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Sapling Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Wheat Growth Modifier: 100%
15.07 20:19:10 [Server] INFO NetherWart Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Nerfing mobs spawned from spawners: false
15.07 20:19:10 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
15.07 20:19:10 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
15.07 20:19:10 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
15.07 20:19:10 [Server] INFO Random Lighting Updates: false
15.07 20:19:10 [Server] INFO Structure Info Saving: true
15.07 20:19:10 [Server] INFO Max Entity Collisions: 8
15.07 20:19:10 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
15.07 20:19:10 [Server] INFO Max TNT Explosions: 100
15.07 20:19:10 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
15.07 20:19:10 [Server] INFO Item Despawn Rate: 6000
15.07 20:19:10 [Server] INFO Item Merge Radius: 2.5
15.07 20:19:10 [Server] INFO Arrow Despawn Rate: 1200
15.07 20:19:10 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
15.07 20:19:10 [Server] INFO View Distance: 10
15.07 20:19:10 [Server] INFO Zombie Aggressive Towards Villager: true
15.07 20:19:10 [Server] INFO Experience Merge Radius: 3.0
15.07 20:19:10 [Server] INFO -------- World Settings For [world_the_end] --------
15.07 20:19:10 [Server] INFO Mob Spawn Range: 4
15.07 20:19:10 [Server] INFO Cactus Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Cane Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Melon Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Mushroom Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Pumpkin Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Sapling Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Wheat Growth Modifier: 100%
15.07 20:19:10 [Server] INFO NetherWart Growth Modifier: 100%
15.07 20:19:10 [Server] INFO Nerfing mobs spawned from spawners: false
15.07 20:19:10 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
15.07 20:19:10 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
15.07 20:19:10 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
15.07 20:19:10 [Server] INFO Random Lighting Updates: false
15.07 20:19:10 [Server] INFO Structure Info Saving: true
15.07 20:19:10 [Server] INFO Max Entity Collisions: 8
15.07 20:19:10 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
15.07 20:19:10 [Server] INFO Max TNT Explosions: 100
15.07 20:19:10 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
15.07 20:19:10 [Server] INFO Item Despawn Rate: 6000
15.07 20:19:10 [Server] INFO Item Merge Radius: 2.5
15.07 20:19:10 [Server] INFO Arrow Despawn Rate: 1200
15.07 20:19:10 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
15.07 20:19:10 [Server] INFO View Distance: 10
15.07 20:19:10 [Server] INFO Zombie Aggressive Towards Villager: true
15.07 20:19:10 [Server] INFO Experience Merge Radius: 3.0
15.07 20:19:10 [Server] INFO Preparing start region for level 0 (Seed: -4948912669493306645)
15.07 20:19:11 [Server] INFO Preparing spawn area: 26%
15.07 20:19:11 [Server] INFO Preparing start region for level 1 (Seed: -4948912669493306645)
15.07 20:19:12 [Server] INFO Preparing start region for level 2 (Seed: -4948912669493306645)
15.07 20:19:12 [Server] INFO Enabling EffectLib v5.1-SNAPSHOT
15.07 20:19:12 [Server] INFO Enabling WorldEdit v6.1.3;7a097ca
15.07 20:19:12 [Server] INFO WEPIF: Using the Bukkit Permissions API.
15.07 20:19:13 [Server] INFO Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_9_R2 as the Bukkit adapter
15.07 20:19:13 [Server] INFO Enabling ViaVersion v0.9.2
15.07 20:19:13 [Server] INFO Enabling MineFortress v1.3.0
15.07 20:19:13 [Server] INFO creating table 'minefortress'
15.07 20:19:13 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
15.07 20:19:13 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
15.07 20:19:13 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
15.07 20:19:13 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
15.07 20:19:13 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
15.07 20:19:13 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2252)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
15.07 20:19:13 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
15.07 20:19:13 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
15.07 20:19:13 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
15.07 20:19:13 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
15.07 20:19:13 [Server] WARN at java.sql.DriverManager.getConnection(Unknown Source)
15.07 20:19:13 [Server] WARN at java.sql.DriverManager.getConnection(Unknown Source)
15.07 20:19:13 [Server] WARN at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:252)
15.07 20:19:13 [Server] WARN at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:184)
15.07 20:19:13 [Server] WARN at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:440)
15.07 20:19:13 [Server] WARN at com.j256.ormlite.table.TableUtils.createTable(TableUtils.java:220)
15.07 20:19:13 [Server] WARN at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:61)
15.07 20:19:13 [Server] WARN at me.tigerhix.minefortress.data.DataManager.setupDatabase(DataManager.java:169)
15.07 20:19:13 [Server] WARN at me.tigerhix.minefortress.data.DataManager.onRegister(DataManager.java:37)
15.07 20:19:13 [Server] WARN at me.tigerhix.framework.commons.behavior.Behavior.register(Behavior.java:15)
15.07 20:19:13 [Server] WARN at me.tigerhix.minefortress.plugin.MineFortress.register(MineFortress.java:47)
15.07 20:19:13 [Server] WARN at me.tigerhix.framework.plugin.GamePlugin.onEnable(GamePlugin.java:76)
15.07 20:19:13 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
15.07 20:19:13 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
15.07 20:19:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
15.07 20:19:13 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361)
15.07 20:19:13 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
15.07 20:19:13 [Server] WARN at java.lang.Thread.run(Unknown Source)
15.07 20:19:13 [Server] WARN Caused by: java.net.ConnectException: Connection refused
15.07 20:19:13 [Server] WARN at java.net.PlainSocketImpl.socketConnect(Native Method)
15.07 20:19:13 [Server] WARN at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
15.07 20:19:13 [Server] WARN at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
15.07 20:19:13 [Server] WARN at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
15.07 20:19:13 [Server] WARN at java.net.SocksSocketImpl.connect(Unknown Source)
15.07 20:19:13 [Server] WARN at java.net.Socket.connect(Unknown Source)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214)
15.07 20:19:13 [Server] WARN at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298)
15.07 20:19:13 [Server] WARN ... 35 more
15.07 20:19:13 [Server] INFO Could not connect to the database. Have you modified database.yml in the plugin folder?
15.07 20:19:13 [Server] INFO Verifying configuration...
15.07 20:19:13 [Server] INFO Verification completed.
15.07 20:19:13 [Server] WARN java.nio.file.NoSuchFileException: plugins/MineFortress/items
15.07 20:19:13 [Server] WARN at sun.nio.fs.UnixException.translateToIOException(Unknown Source)
15.07 20:19:13 [Server] WARN at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
15.07 20:19:13 [Server] WARN at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
15.07 20:19:13 [Server] WARN at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(Unknown Source)
15.07 20:19:13 [Server] WARN at java.nio.file.Files.newDirectoryStream(Unknown Source)
15.07 20:19:13 [Server] WARN at me.tigerhix.minefortress.plugin.config.Conf.load(Conf.java:65)
15.07 20:19:13 [Server] WARN at me.tigerhix.minefortress.plugin.MineFortress.register(MineFortress.java:49)
15.07 20:19:13 [Server] WARN at me.tigerhix.framework.plugin.GamePlugin.onEnable(GamePlugin.java:76)
15.07 20:19:13 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
15.07 20:19:13 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
15.07 20:19:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
15.07 20:19:13 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361)
15.07 20:19:13 [Server] WARN at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268)
15.07 20:19:13 [Server] WARN at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
15.07 20:19:13 [Server] WARN at java.lang.Thread.run(Unknown Source)
15.07 20:19:13 [Server] INFO Item resource files failed to load.
15.07 20:19:13 [Server] INFO Develop mode has been enabled. If you are using the plugin for the first time, type /wizard to get started.
15.07 20:19:13 [Server] INFO Enabling LibsDisguises v9.0.9
15.07 20:19:13 [Server] WARN Lib's Disguises failed to startup, outdated ProtocolLib!
15.07 20:19:13 [Server] WARN You need to update ProtocolLib, please try this build http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/artifact/modules/ProtocolLib/target/ProtocolLib.jar
15.07 20:19:13 [Server] INFO Enabling HolographicDisplays v2.2
15.07 20:19:13 [Server] INFO Found ProtocolLib, adding support for player relative variables.
15.07 20:19:13 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
15.07 20:19:13 [Server] Startup Done (3.918s)! For help, type "help" or "?"
15.07 20:19:13 [Server] INFO Stopping server
15.07 20:19:13 [Server] INFO Disabling HolographicDisplays v2.2
15.07 20:19:13 [Server] INFO Disabling LibsDisguises v9.0.9
15.07 20:19:13 [Server] INFO Disabling MineFortress v1.3.0
15.07 20:19:13 [Server] INFO Disabling ProtocolLib v4.0.2
15.07 20:19:13 [Server] INFO Disabling ViaVersion v0.9.2
15.07 20:19:13 [Server] INFO ViaVersion is disabling, if this is a reload it may not work.
15.07 20:19:13 [Server] INFO Disabling WorldEdit v6.1.3;7a097ca
15.07 20:19:13 [Server] INFO Disabling EffectLib v5.1-SNAPSHOT
15.07 20:19:13 [Server] INFO Saving players
15.07 20:19:13 [Server] INFO Saving worlds
15.07 20:19:13 [Server] INFO Saving chunks for level 'world'/Overworld
15.07 20:19:13 [Server] INFO Saving chunks for level 'world_nether'/Nether
15.07 20:19:13 [Server] INFO Saving chunks for level 'world_the_end'/The End
15.07 20:19:14 [Multicraft] Server shut down (running)
15.07 20:19:14 [Multicraft] Restarting crashed server in 60 seconds
15.07 20:19:14 [Multicraft] Server stopped

**Comment by LCastr0** [comment]
This error has nothing to do with EffectLib. Looks like the problem is in MineFortress.

**Comment by Miljonair12** [comment]
Do you know that i can do?

**Comment by NathanWolf** [comment]
Why do you think this has something to do with EffectLib? 

What is not working exactly?

Yes, Like @LCastr0 said MineFortress is broken, and it looks like LibsDiguises too- that or ProtocolLib needs updating.
```
15.07 20:19:13 [Server] INFO Enabling LibsDisguises v9.0.9
15.07 20:19:13 [Server] WARN Lib's Disguises failed to startup, outdated ProtocolLib!
15.07 20:19:13 [Server] WARN You need to update ProtocolLib, please try this build http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/artifact/modules/ProtocolLib/target/ProtocolLib.j
```

**Comment by NathanWolf** [comment]
You should probably go ask the devs of the plugins that are broken :)
