### ISSUE TITLE
EffectLib 1.10.2

### ISSUE THREAD

**Issue by mickedplay** [Slikey/EffectLib#33]
Hey, is there any version of EffectLib for 1.10.2? Unfortunately I can't find one.

Thanks.

**Comment by NathanWolf** [comment]
There is not an updated version, but there is no need of one. Is something missing for 1.10?

**Comment by mickedplay** [comment]
Uhm, I'm sorry, saw that too late.
![effectlib](https://cloud.githubusercontent.com/assets/17031230/17750510/1f13b670-64c3-11e6-906d-48a921a87d7e.png)

**Comment by NathanWolf** [comment]
Ah, I don't think Curse had an option for 1.10 when I updated.
