### ISSUE TITLE
New update?

### ISSUE THREAD

**Issue by IsS127** [Slikey/EffectLib#35]
Its been 3 days since the spigot version of 1.11,
So i was wondering when the new update for this plugin is comming out?
You know, new particles.
Just wondering :)
Take you're time :)

**Comment by NathanWolf** [comment]
It has been less than 24 hours :)

I'll take a look at the new particle list, I honestly completely forgot.

**Comment by IsS127** [comment]
Oh xD didnt know that, thought it came out 3 days ago.
Take ur time :)
Ty :)

**Comment by LCastr0** [comment]
There are only two new types of particles, the spit, used when llamas spit, and totem, which happens when you activate the totem of undying

**Comment by NathanWolf** [comment]
Also "falling_dust" which sounds cool- though I think that was added in 1.10? EffectLib never got support for it, anyway.

I'm adding all 3 now, shouldn't be a big deal.

**Comment by IsS127** [comment]
ok :)

**Comment by NathanWolf** [comment]
Updated, released as 5.2
