### ISSUE TITLE
This line causes a concurrent modification issue

### ISSUE THREAD

**Issue by iarepandemonium** [Slikey/EffectLib#38]
public void cancel(boolean callback) {
        for (Map.Entry<Effect, BukkitTask> entry : effects.entrySet()) {
            entry.getKey().cancel(callback);
        }
}

**Comment by NathanWolf** [comment]
Oops, looks like you are right. I never use that method myself so I haven't seen it.

Fixed in latest dev build, here:

http://jenkins.elmakers.com/job/EffectLib/103/

And will be in 5.4
