### ISSUE TITLE
Make the EffectManager class non-final

### ISSUE THREAD

**Issue by BlackPhantom3899** [Slikey/EffectLib#41]
I stumbled upon this issue not long ago. I wanted to extend the EffectManager to create an abstract one with a standardized debug behavior and also to perform custom-made operations but I couldn't.

**Comment by NathanWolf** [comment]
Not sure why it was made final, sounds fine to me. Available in current 5.5-SNAPSHOT.

http://jenkins.elmakers.com/job/EffectLib/112/
