### ISSUE TITLE
Release latest build to dev.bukkit

### ISSUE THREAD

**Issue by MWFIAE** [Slikey/EffectLib#45]
When while the latest build be officially available? 
I'm just asking because a very cool feature for betonquest depends on pr #42 and won't get merged until the new version of EffectLib is available. 

Thanks, 
MW

**Comment by NathanWolf** [comment]
Released as 5.5, available via Maven now, pending approval on dev.bukkit.org

**Comment by MWFIAE** [comment]
Thank you! :)
