### ISSUE TITLE
Author,please help me about your effectlib plugin.

### ISSUE THREAD

**Issue by xiaonian233** [Slikey/EffectLib#46]
Hello, author. I like this plugin , and it works well for English words,i'm from China,when i use this draw chinese,it doesn't work,just like a box 
![image](https://user-images.githubusercontent.com/21072615/32980587-1e1937b4-cca4-11e7-8646-739dc79e350b.png) Could you please support chinese character!

thank you very much

**Comment by LCastr0** [comment]
You're probably using a font that cannot render that specific character. You could change the font.
I'm not sure which pluginis TextParticle, if it's yours, then you can just change that by using
`effect.setFont(<font>);`
Arial probably has most of the characters, so I'd suggest that one.
If you're not the author of that plugin, I'd suggest you to leave them a comment about this (and you could link this issue on the comment so they can see how to fix).

**Comment by xiaonian233** [comment]
thank you author,it works !!!!!
