### ISSUE TITLE
Change Entity Particle Location

### ISSUE THREAD

**Issue by Tymmie** [Slikey/EffectLib#47]
Hello!
I've got a issue with your Plugin. I created a HelixEffect and bound it to my player. The problem now is, the particle is in his face, which is fucking up very much xd. So how to change the Y one block down?

**Comment by NathanWolf** [comment]
Set an offset vector with y=-1

https://github.com/Slikey/EffectLib/blob/master/src/main/java/de/slikey/effectlib/Effect.java#L87
