### ISSUE TITLE
Understanding particle offsets

### ISSUE THREAD

**Issue by mcudeveloper** [Slikey/EffectLib#50]
I am trying to create a trail effect, where each waypoint is the location of the player's feet (i.e. the trail follows the player's foot location rather than their head).

Here is my current code with no offsets:

```
TraceEffect trail = new TraceEffect(Cosmetics.em);
trail.particle = ParticleEffect.valueOf(selected);
trail.asynchronous = true;
trail.setEntity(p);
trail.infinite();
trail.start();
```

I have tried things such as 
`trail.offset = new Vector().setY(-2);`

`trail.relativeOffset = new Vector().setY(-2);`

Although these either make no particles show up whatsoever or have no effect. For good measure, I also created two locations of the same X/Z but with a different of 2 on the Y coord and then calculated the vector between those just in case it was me being stupid and not understanding vectors completely.  The particles did not show up when I did this.

I also tried using ``trail.particleOffsetY = -2;`` but this seems to just bug the particles out, sending them into a spasm.

**Comment by NathanWolf** [comment]
Maybe try a Y offset of -1? 

I think -2 is going to just put all the particles in the ground. Players' heads are about 1.6 high I think.

That said, I would think the trail would actually start at feet by default- you're seeing it attach to the player head?

Indeed particleOffsetY is something totally different, that's part of the X,Y,Z offsets used in vanilla particle spawning.

**Comment by mcudeveloper** [comment]
I tried setting the offset to -1 for the Y value; it still doesn't seem to have any effect.
```
							TraceEffect trail = new TraceEffect(Cosmetics.em);
							trail.particle = ParticleEffect.valueOf(selected);
							trail.asynchronous = true;
							trail.setEntity(p);
							//trail.relativeOffset = new Vector().setY(-1);
							trail.offset = new Vector().setY(-1);
							trail.infinite();
							trail.start();
```

**Comment by NathanWolf** [comment]
Ok, sorry, I took a closer look and there were a couple of problems here:

1. setEntity() was broken, not taking the offset into account
2. offset must be set prior to calling setEntity()

If you grab the latest dev build of EffectLib and switch your code around so setEntity() comes after .offset= then it should work.

However note that the current EffectLib builds don't use ParticleEffect anymore so you'd also have to change that to use Particle.

Sorry about that!

Alternately, you can use EffectManager.getEffect to create your effects, which is how I do my own testing, so I didn't realize this other way was broken.

**Comment by mcudeveloper** [comment]
Cheers!
