### ISSUE TITLE
How to make a single particle

### ISSUE THREAD

**Issue by TheJavaDev** [Slikey/EffectLib#55]
I need to make a single particle at a position appear and dissapear. Currently I am using ParticleEffect.display(), but since it is deprecated, is there any other way to do it? Thanks!

**Comment by NathanWolf** [comment]
EffectManager.display is the new way to do that, this works with version-independent code.

https://github.com/Slikey/EffectLib/blob/master/src/main/java/de/slikey/effectlib/EffectManager.java#L79
