### ISSUE TITLE
i cant shade

### ISSUE THREAD

**Issue by abhiram555** [Slikey/EffectLib#58]
hey i tried shade this plugin(new to maven) but still class not found errror

**Comment by abhiram555** [comment]
so if you update shade code it will be good

**Comment by NathanWolf** [comment]
I've added some shading instructions to the readme.

https://github.com/Slikey/EffectLib/blob/master/README.md#how-to-shade

**Comment by abhiram555** [comment]
Okey thanks i got it work thank you verymuch
