### ISSUE TITLE
Deploy to Github Maven Repository

### ISSUE THREAD

**Issue by mixxit** [Slikey/EffectLib#59]
Can you not use the github maven?

**Comment by NathanWolf** [comment]
Power outage. Feel free to mirror it :)

**Comment by NathanWolf** [comment]
Though that said, what exactly do you mean by "github maven"?

I'm not interested in jitpack or anything like that. I don't think github has official support for maven repositories?

**Comment by mixxit** [comment]
Github has its own maven system built in now so you dont have to worry about hosting one

See example project like towny

https://github.com/TownyAdvanced/Towny/packages/27024

**Comment by NathanWolf** [comment]
Interesting- well thanks, I was not aware of that. I don't see a reason not to switch, I'll look into it.

**Comment by NathanWolf** [comment]
EffectLib is now on github, updated README with info.
