### ISSUE TITLE
[1.16 Bug] Certain effects remain still.

### ISSUE THREAD

**Issue by Repo31c** [Slikey/EffectLib#60]
Hello,

I was redirected here by the developer of this plugin:
https://www.spigotmc.org/resources/killeffects-%E2%9C%B4-54-epic-particle-kill-effects-%E2%9C%B4.65879/

I am currently using the latest version of EffectLib with the above plugin and it is able to load on to 1.16, however, certain effects do not function properly and remain even after a player has died. Please look below for an example:
https://cdn.discordapp.com/attachments/724629885997547530/736247197137371146/unknown.png

I am currently using the plugin on the latest 1.16.1 PaperMC build.

**Comment by NathanWolf** [comment]
You need to set `disappearWithOriginEntity=true` to make the effects go away when the entity they're attached to goes away.

This really only effects mobs or players that log out. There is nothing in the plugin that will cancel an effect on player death.
